In [52]:
# 9 Dec 2023
# CSC461 – Assignment4 – NLP
# Aliya Tabassum
# FA21-BSE-089 C
# Compute BoW, TF, IDF, and then TF.IDF values for each term in the following three sentences.

In [43]:
#import warnings to 'ignore' warning messages

import warnings
warnings.filterwarnings("ignore")

In [68]:
#import important libraries

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import manhattan_distances
from sklearn.metrics.pairwise import euclidean_distances

import pandas as pd
import math

In [45]:
#generate two simple texts as examples

S1 = "data science is one of the most important courses in computer science"
S2 = "this is one of the best data science courses"
S3 = "the data scientists perform data analysis"

In [46]:
#combine both texts to make a corpus

data = [S1, S2, S3]
data

['data science is one of the most important courses in computer science',
 'this is one of the best data science courses',
 'the data scientists perform data analysis']

In [48]:
#create a reference object to the CountVectorizer constructor
#use the reference object to generate BoW matrix using the fit_transform() function

count_vectorizer = CountVectorizer()
c_vector_matrix = count_vectorizer.fit_transform(data)

#generate tf.idf matrix using TfidfVectorizer
tfidf_vect_exp = TfidfVectorizer()
tfidf_matrix_exp = tfidf_vect_exp.fit_transform(data)


<3x16 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [7]:
#use get_feature_names_out() to extract vocabulary

c_tokens_exp = count_vectorizer.get_feature_names_out()
c_tokens_exp

array(['analysis', 'best', 'computer', 'courses', 'data', 'important',
       'in', 'is', 'most', 'of', 'one', 'perform', 'science',
       'scientists', 'the', 'this'], dtype=object)

In [8]:
#convert BoW matrix to an array format

vector_array = c_vector_matrix.toarray()
vector_array

array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0]])

In [16]:
#convert BoW matrix to a Pandas dataframe

df_c_exp = pd.DataFrame(data = vector_array, columns = c_tokens_exp)
print("Dataframe of BoW matrix : ",)
df_c_exp


Dataframe of BoW matrix : 


analysis  best  computer  courses  data  important  in  is  most  of  one  \
0         0     0         1        1     1          1   1   1     1   1    1   
1         0     1         0        1     1          0   0   1     0   1    1   
2         1     0         0        0     2          0   0   0     0   0    0   

   perform  science  scientists  the  this  
0        0        2           0    1     0  
1        0        1           0    1     1  
2        1        0           1    1     0

In [17]:
#convert tf.idf matrix to a Pandas dataframe

df_t_exp = pd.DataFrame(data = tfidf_matrix_exp.toarray(), columns = c_tokens_exp)
print("Dataframe of tf.idf matrix : ")
df_t_exp

Dataframe of tf.idf matrix : 


analysis      best  computer   courses      data  important        in  \
0  0.000000  0.000000  0.327476  0.249054  0.193412   0.327476  0.327476   
1  0.000000  0.422968  0.000000  0.321678  0.249812   0.000000  0.000000   
2  0.459115  0.000000  0.000000  0.000000  0.542321   0.000000  0.000000   

         is      most        of       one   perform   science  scientists  \
0  0.249054  0.327476  0.249054  0.249054  0.000000  0.498107    0.000000   
1  0.321678  0.000000  0.321678  0.321678  0.000000  0.321678    0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.459115  0.000000    0.459115   

        the      this  
0  0.193412  0.000000  
1  0.249812  0.422968  
2  0.271161  0.000000

In [23]:
#generate tf matrix
tf_matrix = vector_array / vector_array.sum(axis=1, keepdims=True)
print("Tf Matrix : \n",tf_matrix)

#convert tf matrix to a Pandas dataframe
df_tf_exp = pd.DataFrame(data = tf_matrix, columns = c_tokens_exp)
print("Dataframe of tf matrix : ")
df_tf_exp

Tf Matrix : 
 [[0.         0.         0.08333333 0.08333333 0.08333333 0.08333333
  0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.
  0.16666667 0.         0.08333333 0.        ]
 [0.         0.11111111 0.         0.11111111 0.11111111 0.
  0.         0.11111111 0.         0.11111111 0.11111111 0.
  0.11111111 0.         0.11111111 0.11111111]
 [0.16666667 0.         0.         0.         0.33333333 0.
  0.         0.         0.         0.         0.         0.16666667
  0.         0.16666667 0.16666667 0.        ]]
Dataframe of tf matrix : 


analysis      best  computer   courses      data  important        in  \
0  0.000000  0.000000  0.083333  0.083333  0.083333   0.083333  0.083333   
1  0.000000  0.111111  0.000000  0.111111  0.111111   0.000000  0.000000   
2  0.166667  0.000000  0.000000  0.000000  0.333333   0.000000  0.000000   

         is      most        of       one   perform   science  scientists  \
0  0.083333  0.083333  0.083333  0.083333  0.000000  0.166667    0.000000   
1  0.111111  0.000000  0.111111  0.111111  0.000000  0.111111    0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.166667  0.000000    0.166667   

        the      this  
0  0.083333  0.000000  
1  0.111111  0.111111  
2  0.166667  0.000000

In [24]:
#sum of doc, words appear in.
num_data = len(vector_array)
num_terms = len(vector_array[0])
sum_list = []
for i in range(num_terms):
  count = 0
  for j in range(num_data):
    if(vector_array[j][i] > 0):
       count += 1
  sum_list.append(count)
sum_list

[1, 1, 1, 2, 3, 1, 1, 2, 1, 2, 2, 1, 2, 1, 3, 1]

In [39]:
#idf matrix
idf_matrix = []
for i in range(num_terms):
  idf_matrix.append(math.log10(num_data/sum_list[i]))
print("Idf matrix : \n",idf_matrix )


#convert idf matrix to a Pandas dataframe
df_idf_exp = pd.DataFrame(data = idf_matrix)
print("Dataframe of idf matrix : \n")
df_idf_exp



Idf matrix : 
 [0.47712125471966244, 0.47712125471966244, 0.47712125471966244, 0.17609125905568124, 0.0, 0.47712125471966244, 0.47712125471966244, 0.17609125905568124, 0.47712125471966244, 0.17609125905568124, 0.17609125905568124, 0.47712125471966244, 0.17609125905568124, 0.47712125471966244, 0.0, 0.47712125471966244]
Dataframe of idf matrix : 



0
0   0.477121
1   0.477121
2   0.477121
3   0.176091
4   0.000000
5   0.477121
6   0.477121
7   0.176091
8   0.477121
9   0.176091
10  0.176091
11  0.477121
12  0.176091
13  0.477121
14  0.000000
15  0.477121

In [40]:
#tf.idf matrix through manual calculate tf and idf matrix
tf_idf_matrix = {}
for i in range(num_terms):
  tf_idf_matrix = tf_matrix*idf_matrix
print("tf.idf matrix : \n",tf_idf_matrix )

#convert tf.idf matrix to a Pandas dataframe
df_tf_idf_exp = pd.DataFrame(data = tf_idf_matrix, columns = c_tokens_exp)
print("Dataframe of tf.idf matrix : ")
df_tf_idf_exp

tf.idf matrix : 
 [[0.         0.         0.0397601  0.01467427 0.         0.0397601
  0.0397601  0.01467427 0.0397601  0.01467427 0.01467427 0.
  0.02934854 0.         0.         0.        ]
 [0.         0.05301347 0.         0.0195657  0.         0.
  0.         0.0195657  0.         0.0195657  0.0195657  0.
  0.0195657  0.         0.         0.05301347]
 [0.07952021 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.07952021
  0.         0.07952021 0.         0.        ]]
Dataframe of tf.idf matrix : 


analysis      best  computer   courses  data  important       in        is  \
0   0.00000  0.000000   0.03976  0.014674   0.0    0.03976  0.03976  0.014674   
1   0.00000  0.053013   0.00000  0.019566   0.0    0.00000  0.00000  0.019566   
2   0.07952  0.000000   0.00000  0.000000   0.0    0.00000  0.00000  0.000000   

      most        of       one  perform   science  scientists  the      this  
0  0.03976  0.014674  0.014674  0.00000  0.029349     0.00000  0.0  0.000000  
1  0.00000  0.019566  0.019566  0.00000  0.019566     0.00000  0.0  0.053013  
2  0.00000  0.000000  0.000000  0.07952  0.000000     0.07952  0.0  0.000000

In [55]:
#generate similarity matrix
#Similarity matrixes of BoW vector matrix
c_cosine_similarity_matrix = cosine_similarity(c_vector_matrix)
vec_manhattan_dist = manhattan_distances(c_vector_matrix)
vec_euclidean_dist = euclidean_distances(c_vector_matrix)
print("\BoW vector Matrix: \n")

print("\nCosine Similarity:")
print(c_cosine_similarity_matrix)

print("\nManhattan Distance:")
print(vec_manhattan_dist)

print("\nEuclidean Distance:")
print(vec_euclidean_dist)


\BoW vector Matrix: 


Cosine Similarity:
[[1.         0.71269665 0.28347335]
 [0.71269665 1.         0.35355339]
 [0.28347335 0.35355339 1.        ]]

Manhattan Distance:
[[ 0.  7. 14.]
 [ 7.  0. 11.]
 [14. 11.  0.]]

Euclidean Distance:
[[0.         2.64575131 4.        ]
 [2.64575131 0.         3.31662479]
 [4.         3.31662479 0.        ]]


In [56]:
#Similarity matrixes of tf.idf(through TfidfVectorizer) matrix
tfidf_cosine_similarity = cosine_similarity(tfidf_matrix_exp)
tfidf_manhattan_dist = manhattan_distances(tfidf_matrix_exp)
tfidf_euclidean_dist = euclidean_distances(tfidf_matrix_exp)
print("\ntf.idf Matrix: \n")

print("\nCosine Similarity:")
print(tfidf_cosine_similarity)

print("\nManhattan Distance:")
print(tfidf_manhattan_dist)

print("\nEuclidean Distance:")
print(tfidf_euclidean_dist)


tf.idf Matrix: 


Cosine Similarity:
[[1.         0.57732419 0.15733751]
 [0.57732419 1.         0.20321737]
 [0.15733751 0.20321737 1.        ]]

Manhattan Distance:
[[0.         2.73556468 4.60822682]
 [2.73556468 0.         4.14553005]
 [4.60822682 4.14553005 0.        ]]

Euclidean Distance:
[[0.         0.91943005 1.29820067]
 [0.91943005 0.         1.26236494]
 [1.29820067 1.26236494 0.        ]]


In [57]:
#Similarity matrixes of tf.idf matrix
tf_idf_cosine_similarity = cosine_similarity(tf_idf_matrix)
tf_idf_manhattan_dist = manhattan_distances(tf_idf_matrix)
tf_idf_euclidean_dist = euclidean_distances(tf_idf_matrix)
print("\ntf.idf Matrix: \n")

print("\nCosine Similarity:")
print(tf_idf_cosine_similarity)

print("\nManhattan Distance:")
print(tf_idf_manhattan_dist)

print("\nEuclidean Distance:")
print(tf_idf_euclidean_dist)


tf.idf Matrix: 


Cosine Similarity:
[[1.         0.22124298 0.        ]
 [0.22124298 1.         0.        ]
 [0.         0.         1.        ]]

Manhattan Distance:
[[0.         0.29441591 0.48564668]
 [0.29441591 0.         0.44241605]
 [0.48564668 0.44241605 0.        ]]

Euclidean Distance:
[[0.         0.11016228 0.16436705]
 [0.11016228 0.         0.16280458]
 [0.16436705 0.16280458 0.        ]]
